name: bumdest
description: BUMD Investment
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  nav: ^1.1.3
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.1+1
  cached_network_image: ^3.2.1
  ionicons: ^0.1.2
  google_nav_bar: ^5.0.6
  infinite_scroll_pagination: ^3.2.0
  carousel_slider: ^4.1.1
  bottom_sheet: ^3.1.1
  easy_pdf_viewer: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/icons/bumdest_full.png
  adaptive_icon_background: assets/icons/bumdest_background.png
  adaptive_icon_foreground: assets/icons/bumdest_foreground.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Finlandica
      fonts:
        - asset: assets/fonts/Finlandica-Regular.ttf
          weight: 400
        - asset: assets/fonts/Finlandica-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Finlandica-Medium.ttf
          weight: 500
        - asset: assets/fonts/Finlandica-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Finlandica-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Finlandica-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Finlandica-Bold.ttf
          weight: 700
        - asset: assets/fonts/Finlandica-BoldItalic.ttf
          weight: 700
          style: italic
